const showTableData = [
    {
        name:'图片',
        value:'cover',
        width:'110'
    },
    {
        name:'活动名称',
        value:'activity_name',
        width:'120'
    },
    {
        name:'H5链接',
        value:'link',
        width:'120'
    },
    {
        name:'公司',
        value:'companyName',
        width:'120'
    },
    {
        name:'位置',
        value:'position',
        width:'120'
    },
    {
        name:'备注',
        value:'remarks',
        width:'120'
    },
    {
        name:'项目数量',
        value:'itemNumber',
        width:'90'
    },
    {
        name:'创建人',
        value:'createByName',
        width:'100'
    },
    {
        name:'创建时间',
        value:'create_time',
        width:'110'
    },
    {
        name:'上架时间',
        value:'dismounted_time',
        width:'100'
    },
    {
        name:'下架时间',
        value:'added_time',
        width:'110'
    },
    {
        name:'上下架状态',
        value:'upper_lower_shelf_status',
        width:'110'
    },
    {
        name:'操作',
        value:'name',
        width:'120'
    }
]
export {showTableData}