const showTableData = [
    {
        name:'活动名称',
        value:'activityName',
        width:'120'
    },
    {
        name:'公司',
        value:'companyName',
        width:'120'
    },
    {
        name:'备注',
        value:'remarks',
        width:'120'
    },
    {
        name:'位置',
        value:'position',
        width:'120'
    },
    {
        name:'项目数量',
        value:'itemNumber',
        width:'90'
    },
    {
        name:'生效开始时间',
        value:'effectiveStartTime',
        width:'110'
    },
    {
        name:'生效结束时间',
        value:'effectiveEndTime',
        width:'110'
    },
    {
        name:'生效区间',
        value:'activityDuration',
        width:'100'
    },
    {
        name:'创建时间',
        value:'createTime',
        width:'110'
    },
    {
        name:'上架时间',
        value:'upperShelfTime',
        width:'110'
    },
    {
        name:'下架时间',
        value:'lowerShelftime',
        width:'110'
    },
    {
        name:'创建人',
        value:'createPeople',
        width:'100'
    },
    {
        name:'领取数',
        value:'recipientsNumber',
        width:'100'
    },
    {
        name:'活动状态',
        value:'activityState',
        width:'90'
    },
    {
        name:'上下架状态',
        value:'upperLowerRackState',
        width:'90'
    },
    {
        name:'操作',
        value:'name',
        width:'120'
    }
]
export {showTableData}