const showTableData = [
    {
        name:"所属公司",
        value:'affiliatedCompany',
        width:'110'
    },
    {
        name:"发布内容",
        value:'content',
        width:'145'
    },
    {
        name:"图片",
        value:'picture',
        width:'90'
    },
    {
        name:"发布人",
        value:'publisher',
        width:'90'
    },
    {
        name:"动态时间",
        value:'dynamic_time',
        width:'110'
    },
    {
        name:"发布时间",
        value:'create_time',
        width:'110'
    },
    {
        name:"操作",
        value:'company',
        width:'110'
    }
]
export {showTableData}