const showTableData = [
    {
        name:"活动名称",
        value:"activity_name",
        width:"120"
    },
    {
        name:"城市",
        value:"city",
        width:"100"
    },
    {
        name:"获客渠道",
        value:"platform",
        width:"100"
    },
    {
        name:"客户电话",
        value:"customer_telephone",
        width:"100"
    },
    {
        name:"意向项目",
        value:"bName",
        width:"120"
    },  
    {
        name:"项目价格",
        value:"building_price",
        width:"100"
    },
    {
        name:"优惠码",
        value:"preference_code",
        width:"100"
    },
    {
        name:"领取时间",
        value:"collection_time",
        width:"100"
    },
    {
        name:"负责人",
        value:"eName",
        width:"100"
    },
]
export {showTableData}